### PR TITLE
Feature/issue#2 fix neg error

### LINKED ISSUE #2: won't let me put negative values in to take away some of the review days I added
messed up and added 2 days to ALL reviews rather than the decks I needed to postpone. I have to review cards for my test in 2 days and just read the deal about the code messing up if I try to custom study and review ahead. what should I do??

### PR DESCRIPTION
**Pull request by jasonsparc**
Fixes #2

### CODE REVIEW

**Comment by jasonsparc** [comment]
@Arthur-Milchior Also, should I set `"coefficient for negative"` to `true` by default, i.e., change `config.json` into:

```json
{"interval coefficient": 0.33,"coefficient for negative": true}
```

…so that, if say I inputted `5` and then later on changed my mind, I can easily undo it with `-5` without having to fiddle with the configs and flipping `"coefficient for negative"` to `true` instead.

**Comment by jasonsparc** [comment]
^ my guess is that, they'll probably going to use the “*negative days*”-feature much more often for that specific purpose.

**Comment by neuroblastommy** [comment]
> ^ my guess is that, they'll probably going to use the “_negative days_”-feature much more often for that specific purpose.

panicked med students can confirm**

**Comment by jasonsparc** [comment]
@Arthur-Milchior Alternatively, upon detection of a *negative days* input, search first for review cards whose interval is less than or equal to the absolute value of the resulting *interval decrease*, i.e., the `ivlDelay` variable I created under `def addDelay(…)`

If there are such cards, either abort the operation or ask the user before proceeding. Maybe through another config that bypasses the *abort*-case? So that it'll ask instead to proceed if that config is on?

**Comment by jasonsparc** [comment]
And by *alternatively*, what I really meant to say was, *“in addition to…”* 😝

**Comment by jasonsparc** [comment]
^ Also, that new config I was proposing about is for people who just loves hitting “yes” without reading the dialog text. So that it won't be accident-prone.

**Pull request merged**
